// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_Two_Forms_One_Page.Models;

namespace _01_Two_Forms_One_Page.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20211209234317_OkMaybeImTheSillyGoose")]
    partial class OkMaybeImTheSillyGoose
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_01_Two_Forms_One_Page.Models.Duck", b =>
                {
                    b.Property<int>("DuckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BillLength")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DuckName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Quackifications")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DuckId");

                    b.ToTable("Ducks");
                });

            modelBuilder.Entity("_01_Two_Forms_One_Page.Models.Goose", b =>
                {
                    b.Property<int>("GooseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GooseFrabba")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GooseName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GooseId");

                    b.ToTable("Geese");
                });
#pragma warning restore 612, 618
        }
    }
}
